/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package atmani.art.project.v1.api;

import atmani.art.project.v1.model.Category;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.5.0")
@Validated
@Controller
public interface CategoriesApi {

    /**
     * GET /categories : Returns a list of categories
     *
     * @return A list of categories (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/categories",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Category>> categoriesGet(
        
    );


    /**
     * DELETE /categories/{id} : Delete category by ID
     *
     * @param id Category ID (required)
     * @return Category deleted successfully (no content) (status code 204)
     */
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/categories/{id}"
    )
    
    ResponseEntity<Void> categoriesIdDelete(
         @PathVariable("id") Long id
    );


    /**
     * GET /categories/{id} : Get category by ID
     *
     * @param id Category ID (required)
     * @return Category information (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/categories/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Category> categoriesIdGet(
         @PathVariable("id") Long id
    );


    /**
     * PUT /categories/{id} : Update category
     *
     * @param id Category ID (required)
     * @param category Category object that needs to be updated (required)
     * @return Category updated successfully (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/categories/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Category> categoriesIdPut(
         @PathVariable("id") Long id,
         @Valid @RequestBody Category category
    );


    /**
     * POST /categories : Add a new category
     *
     * @param category Category object that needs to be created (required)
     * @return Category created (status code 201)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/categories",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Category> categoriesPost(
         @Valid @RequestBody Category category
    );

}
