/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package atmani.art.project.v1.api;

import atmani.art.project.v1.model.Product;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.5.0")
@Validated
@Controller
public interface ProductsApi {

    /**
     * GET /products : Returns a list of products
     *
     * @return A list of products (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/products",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Product>> productsGet(
        
    );


    /**
     * DELETE /products/{id} : Delete product by ID
     *
     * @param id Product ID (required)
     * @return Product deleted successfully (no content) (status code 204)
     */
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/products/{id}"
    )
    
    ResponseEntity<Void> productsIdDelete(
         @PathVariable("id") Long id
    );


    /**
     * GET /products/{id} : Get product by ID
     *
     * @param id Product ID (required)
     * @return Product information (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/products/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Product> productsIdGet(
         @PathVariable("id") Long id
    );


    /**
     * PUT /products/{id} : Update product
     *
     * @param id Product ID (required)
     * @param product Product object that needs to be updated (required)
     * @return Product updated successfully (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/products/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Product> productsIdPut(
         @PathVariable("id") Long id,
         @Valid @RequestBody Product product
    );


    /**
     * POST /products : Add a new product
     *
     * @param product Product object that needs to be created (required)
     * @return Product created (status code 201)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/products",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Product> productsPost(
         @Valid @RequestBody Product product
    );

}
